version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn clean install -DskipTests=true
  pre_build:
    commands:
      - cd backend
  build:
    commands:
      - mvn package -DskipTests=true
  post_build:
    commands:
      - mv target/*.jar application.jar
      - zip -r application.zip application.jar
artifacts:
  files:
    - application.zip
  discard-paths: yes
