version: 0.2 # Versão do buildspec

phases:
  install:
    runtime-versions:
      java: corretto17 # Use a versão do Java que você está usando (ex: corretto11, corretto21)
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install -DskipTests=true # Instala dependências e pula testes para agilizar o build. Considere rodar testes em um ambiente de produção.
  build:
    commands:
      - echo "Building the JAR file..."
      - mvn package -DskipTests=true # Empacota a aplicação em um JAR
  post_build:
    commands:
      - echo "Build completed. Moving artifact..."
      - mv target/*.jar application.jar # Renomeia o JAR gerado para 'application.jar' (nome genérico)
      - zip -r application.zip application.jar # Zipal o JAR para o Elastic Beanstalk

artifacts:
  files:
    - application.zip # Define o arquivo que será o artefato do build
  discard-paths: yes # Não inclui a estrutura de pastas do build no artefato