version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # <--- Verifique e ajuste para a versão do seu JDK (ex: corretto11, corretto21)
    commands:
      - echo "Instalando dependências Maven..."
      - mvn clean install -DskipTests=true
  pre_build: # <--- Esta fase
    commands: # <--- Este "commands" deve estar alinhado com "install" e "build"
      - echo "Navegando para o diretório do projeto: backend"
      - cd backend # <--- ENTRE NESTA PASTA!
  build: # <--- Esta fase
    commands: # <--- Este "commands" deve estar alinhado com "install" e "pre_build"
      - echo "Construindo o arquivo JAR..."
      - mvn package -DskipTests=true # Não precisa de --file pom.xml se você já está na pasta
  post_build:
    commands:
      - echo "Build concluído. Movendo artefato..."
      - mv target/*.jar application.jar # O JAR estará em backend/target
      - zip -r application.zip application.jar # Zipal o JAR para o Elastic Beanstalk

artifacts:
  files:
    - application.zip # Este é o arquivo que será o artefato final
  discard-paths: yes # Não inclui a estrutura de pastas no artefato ZIP final